version: "3.9"
   
services:
  app:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    container_name: AppServer
    volumes:
      - .:/AppServer
    ports:
      - "8000:8000"
    environment:
      - REDIS_NAME=redis
      - REDIS_USER=redis
      - REDIS_PASSWORD=redis
    depends_on:
      - redis