
version: '3'

services:

  shard5svr1:
    container_name: shard5svr1
    image: mongo
    command: mongod --shardsvr --replSet shard5rs --port 27017 --dbpath /data/db
    ports:
      - 50013:27017
    volumes:
      - shard5svr1:/data/db

  shard5svr2:
    container_name: shard5svr2
    image: mongo
    command: mongod --shardsvr --replSet shard5rs --port 27017 --dbpath /data/db
    ports:
      - 50014:27017
    volumes:
      - shard5svr2:/data/db

  shard5svr3:
    container_name: shard5svr3
    image: mongo
    command: mongod --shardsvr --replSet shard5rs --port 27017 --dbpath /data/db
    ports:
      - 50015:27017
    volumes:
      - shard5svr3:/data/db

networks: 
  default: 
    external:
      name: dta

volumes:
  shard5svr1: {}
  shard5svr2: {}
  shard5svr3: {}

