version: '3'

services:
  cfgsvr1:
    container_name: cfgsvr1
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40001:27017
    volumes:
      - cfgsvr1:/data/db

  cfgsvr2:
    container_name: cfgsvr2
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40002:27017
    volumes:
      - cfgsvr2:/data/db

  cfgsvr3:
    container_name: cfgsvr3
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40003:27017
    volumes:
      - cfgsvr3:/data/db

  cfgsvr4:
    container_name: cfgsvr4
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40004:27017
    volumes:
      - cfgsvr4:/data/db
  cfgsvr5: 
    container_name: cfgsvr5
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40005:27017
    volumes:
      - cfgsvr5:/data/db
networks: 
  default: 
    external: 
      name: dta

volumes:
  cfgsvr1: {}
  cfgsvr2: {}
  cfgsvr3: {}
  cfgsvr4: {}
  cfgsvr5: {}
