version: '3'
services:
  nginx:
    build:
      context : ./nginx/
      dockerfile: Nginx.Dockerfile
    depends_on:
      - api
    ports:
      - "5100:5100"
    restart: always
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    command: redis-server
  api:
    build: .
    command: python -m gunicorn TransactionServer.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env
    restart: always

networkss:
  default: 
    external: 
      name: dta

  
  
  