version: '3.4'
services:
  nginx:
    build:
      context : ./nginx/
      dockerfile: Nginx.Dockerfile
    depends_on:
      - api
    ports:
      - "5100:5100"
    restart: always
  api:
    build: .
    command: python -m gunicorn transactionserver.wsgi:application -bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
    restart: always
  
  